# Generated by Django 2.0 on 2017-12-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AhPets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatureId', models.IntegerField()),
                ('creatureName', models.CharField(max_length=25)),
                ('cost', models.TextField()),
                ('time_left', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatureId', models.IntegerField()),
                ('creatureName', models.CharField(max_length=25)),
                ('collected', models.BooleanField(default=0)),
            ],
        ),
    ]
