# Generated by Django 2.0 on 2017-12-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionpets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='itemId',
            field=models.IntegerField(default=0),
        ),
    ]
