# Generated by Django 2.0 on 2017-12-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionpets', '0002_pets_itemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='itemId',
            new_name='speciesId',
        ),
        migrations.RemoveField(
            model_name='ahpets',
            name='creatureId',
        ),
        migrations.AddField(
            model_name='ahpets',
            name='speciesId',
            field=models.IntegerField(default=0),
        ),
    ]
