# Generated by Django 2.0 on 2017-12-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionpets', '0003_auto_20171228_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahpets',
            name='creatureId',
            field=models.IntegerField(default=0),
        ),
    ]
